######################################################################
# Automatically generated by qmake (3.0) ?? 10? 2 00:58:27 2017
######################################################################

QT += core gui widgets

TEMPLATE = app
TARGET = qscreenfetch
INCLUDEPATH += .

# Input
HEADERS += main_window.h utils.h
SOURCES += main.cpp main_window.cpp utils.cpp
